language: ruby
rvm:
  - 2.6.3

install:
  - bundle install
env:
  - DB_HOST=localhost RAILS_ENV=test



script:
  - rails db:create db:structure:load
  - rails standard
  - rails test
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12

cache:
  - bundler
  - apt
