language: ruby
rvm:
  - 2.6.3

before_install:
  - cp config/database.yml.travis config/database.yml
install:
  - bundle install --with='test'
env:
  global:
    - DB_HOST=localhost
    - RAILS_ENV=test
    - PGVER=12
    - PGPORT=5433

script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - rails db:structure:load
  - rails standard
  - rails test
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12
cache:
  directories:
    - /home/travis/.rvm/
    - /var/cache/apt