language: ruby
rvm:
  - 2.6.3

before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - cp config/database.yml.travis config/database.yml
install:
  - bundle install --with='test'
env:
  global:
    - DB_HOST=localhost
    - RAILS_ENV=test



script:
  - systemctl -l status postgresql@12-main
  - rails db:create db:structure:load
  - rails standard
  - rails test
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12
cache:
  directories:
    - vendor/bundle
    - /var/cache/apt