language: ruby
rvm:
  - 2.6.3

before_install:
  - cp config/database.yml.travis config/database.yml
  - /usr/lib/postgresql/12/bin/pg_ctl -D /var/lib/postgresql/12/main -l logfile start
install:
  - bundle install --with='test'
env:
  - DB_HOST=localhost RAILS_ENV=test



script:
  - rails db:create db:structure:load
  - rails standard
  - rails test
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12
cache:
  directories:
    - vendor/bundle
    - /var/cache/apt